#!/usr/bin/env bun
/**
 * CLI Generator — reads api-registry.ts and generates Commander.js commands.
 *
 * Usage: bun run generator/generate.ts [--verify-only]
 *
 * - Without flags: generates src/generated/*.ts files
 * - With --verify-only: only verifies registry against api-client source (no file output)
 */

import * as fs from 'fs';
import * as path from 'path';
import { API_REGISTRY, countMethods, type ServiceDef, type MethodDef } from './api-registry';

// ─── Logical Unit Types ──────────────────────────────────────────────

type UnitArgDef = {
  name: string;
  description: string;
  required: boolean;
  type: 'string' | 'number';
};

type UnitOptionDef = {
  name: string;
  description: string;
  type: 'string' | 'number' | 'boolean';
  required?: boolean;
  defaultValue?: string | number | boolean;
};

type UnitTableColumn = {
  key: string;
  label?: string;
  maxWidth?: number;
};

type UnitTable = {
  emptyMessage: string;
  columns: UnitTableColumn[];
  /** If set, the response is an array of components; extract this field's array from each */
  flatten?: string;
};

type UnitCommandDef = {
  name: string;
  description: string;
  service: string;
  subGroup?: string;
  atomicRef: string;
  httpMethod: string;
  urlTemplate: string;
  idCount: number;
  args: UnitArgDef[];
  options: UnitOptionDef[];
  table?: UnitTable;
  /** Hardcoded positional args injected into the URL template (e.g. { "0": "keboola.orchestrator" }) */
  hardcodedArgs?: Record<string, string>;
  /** Maps CLI arg names to URL template positions (e.g. { "flowId": 1 }) */
  argMapping?: Record<string, number>;
  /** Additional query params merged as defaults */
  queryDefaults?: Record<string, string>;
  /** Build a custom request body; $varName references args/options */
  buildBody?: Record<string, string>;
};

type UnitDef = {
  name: string;
  description: string;
  skillDescription?: string;
  commands: UnitCommandDef[];
};

type LogicalUnitsFile = {
  units: UnitDef[];
};

const GENERATED_DIR = path.resolve(import.meta.dir, '../src/generated');
const HEADER = `// AUTO-GENERATED by generator/generate.ts — DO NOT EDIT
// Re-generate with: make generate
`;

// ─── Verification ─────────────────────────────────────────────────────

const API_CLIENT_DIR = path.resolve(import.meta.dir, '../../ui/packages/api-client/src/clients');

function extractExportedMethods(filePath: string): string[] {
  if (!fs.existsSync(filePath)) {
    return [];
  }
  const source = fs.readFileSync(filePath, 'utf-8');

  // Find the return { ... } block at the end of the factory function
  // We look for the last return { ... }; pattern
  const returnBlocks = source.matchAll(/return\s*\{([^}]+)\}/g);
  let lastMatch: string | null = null;
  for (const match of returnBlocks) {
    lastMatch = match[1]!;
  }

  if (!lastMatch) return [];

  // Extract method names from the return object
  return lastMatch
    .split(',')
    .map((s) => s.replace(/\/\/.*$/gm, '').trim()) // remove comments
    .filter((s) => s.length > 0 && !s.startsWith('//'))
    .map((s) => {
      // Handle "foo: bar" and just "foo"
      const colonIndex = s.indexOf(':');
      if (colonIndex > 0) {
        return s.substring(0, colonIndex).trim();
      }
      return s.trim();
    })
    .filter((s) => s.length > 0 && /^[a-zA-Z_]/.test(s));
}

type VerifyResult = {
  ok: boolean;
  errors: string[];
  warnings: string[];
};

function verifyRegistry(): VerifyResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  for (const service of API_REGISTRY) {
    const clientDir = path.join(API_CLIENT_DIR, service.sourceDir);

    if (!fs.existsSync(clientDir)) {
      warnings.push(`[${service.name}] Source directory not found: ${clientDir}`);
      continue;
    }

    // Verify direct methods on the main client file
    const mainFile = path.join(clientDir, service.clientFile);
    const mainMethods = extractExportedMethods(mainFile);

    for (const method of service.methods) {
      // Skip methods that are actually on sub-objects (handled by sub-groups)
      if (!mainMethods.includes(method.name)) {
        // Check if it might be a private method (prefixed with _)
        if (!mainMethods.includes(`_${method.name}`)) {
          errors.push(`[${service.name}] Method '${method.name}' not found in ${service.clientFile}. Available: ${mainMethods.join(', ')}`);
        }
      }
    }

    // Verify sub-group methods
    for (const group of service.subGroups) {
      const subFile = path.join(clientDir, group.sourceFile);
      const subMethods = extractExportedMethods(subFile);

      if (subMethods.length === 0) {
        warnings.push(`[${service.name}.${group.name}] No methods found in ${group.sourceFile}`);
        continue;
      }

      for (const method of group.methods) {
        if (!subMethods.includes(method.name)) {
          errors.push(`[${service.name}.${group.name}] Method '${method.name}' not found in ${group.sourceFile}. Available: ${subMethods.join(', ')}`);
        }
      }

      // Warn about methods in source but not in registry
      const registeredNames = new Set(group.methods.map((m) => m.name));
      for (const srcMethod of subMethods) {
        if (!registeredNames.has(srcMethod) && !srcMethod.startsWith('_')) {
          warnings.push(`[${service.name}.${group.name}] Method '${srcMethod}' exists in source but not in registry`);
        }
      }
    }

    // Warn about methods in source but not in registry (direct methods)
    const registeredDirectNames = new Set(service.methods.map((m) => m.name));
    // For the main client, also collect sub-group names (they appear in return)
    const subGroupNames = new Set(service.subGroups.map((g) => g.name));
    for (const srcMethod of mainMethods) {
      if (!registeredDirectNames.has(srcMethod) && !subGroupNames.has(srcMethod) && !srcMethod.startsWith('_')) {
        warnings.push(`[${service.name}] Method '${srcMethod}' exists in source but not in registry`);
      }
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
  };
}

// ─── Code Generation ──────────────────────────────────────────────────

function camelToKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function kebabToCamel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function pascalCase(name: string): string {
  return name.split('-').map((s) => s[0]!.toUpperCase() + s.slice(1)).join('');
}

/** Map service to its CliContext accessor. All are async except storage. */
function getApiCall(service: ServiceDef): string {
  const map: Record<string, string> = {
    'data-science': 'ctx.dataScienceApi()',
    'storage': 'ctx.storageApi()',
    'vault': 'ctx.vaultApi()',
    'management': 'ctx.managementApi()',
    'queue': 'ctx.queueApi()',
    'sandboxes': 'ctx.sandboxesApi()',
    'editor': 'ctx.editorApi()',
    'encryption': 'ctx.encryptionApi()',
    'chat': 'ctx.chatApi()',
    'ai': 'ctx.aiApi()',
    'query-service': 'ctx.queryServiceApi()',
    'metastore': 'ctx.metastoreApi()',
    'sync-actions': 'ctx.syncActionsApi()',
    'status': 'ctx.statusApi()',
    'assets': 'ctx.assetsApi()',
    'telemetry': 'ctx.telemetryApi()',
  };
  return map[service.name] ?? `ctx.genericServiceApi('${service.name}')`;
}

function isAsyncApi(service: ServiceDef): boolean {
  return service.name !== 'storage';
}

function buildCallArgs(method: MethodDef): { preamble: string; callArgs: string } {
  const hasJsonData = method.options.some((o) => o.type === 'json' && o.name === 'data');
  let preamble = '';
  if (hasJsonData) {
    preamble = `        const bodyData = opts.data ? JSON.parse(opts.data) : {};\n`;
  }

  // Separate ID positional args (consumed by URL template) from non-ID positional args
  const idArgs = method.args.slice(0, method.idCount);
  const nonIdArgs = method.args.slice(method.idCount);

  // ID args are passed as separate positional params (they go into URL placeholders)
  const args: string[] = [];
  for (const arg of idArgs) {
    args.push(arg.type === 'number' ? `Number(${arg.name})` : arg.name);
  }

  // Non-ID positional args + options are merged into a single object.
  // This ensures buildPathFromMethod always receives an object at args[idCount].
  const nonIdEntries = nonIdArgs.map((a) => {
    const cn = kebabToCamel(a.name);
    return a.type === 'number' ? `${cn}: Number(${a.name})` : `${cn}: ${a.name}`;
  });
  const qpSet = new Set((method.queryParams ?? []).map(kebabToCamel));
  const nonDataOpts = method.options.filter((o) => o.name !== 'data' && !qpSet.has(kebabToCamel(o.name)));
  const optEntries = nonDataOpts.map((o) => {
    const cn = kebabToCamel(o.name);
    return o.type === 'number'
      ? `${cn}: opts['${cn}'] !== undefined ? Number(opts['${cn}']) : undefined`
      : `${cn}: opts['${cn}']`;
  });

  if (hasJsonData) {
    const extras = [...nonIdEntries, ...optEntries];
    if (extras.length === 0) {
      args.push('bodyData');
    } else {
      args.push(`{ ...bodyData, ${extras.join(', ')} }`);
    }
  } else if (nonIdEntries.length > 0 || optEntries.length > 0) {
    args.push(`{ ${[...nonIdEntries, ...optEntries].join(', ')} }`);
  }
  return { preamble, callArgs: args.join(', ') };
}

function generateCommand(
  method: MethodDef,
  parentVar: string,
  apiExpr: string,
  asyncApi: boolean,
  subGroupName?: string,
): string {
  const lines: string[] = [];
  const argStr = method.args
    .map((a) => (a.required ? `<${camelToKebab(a.name)}>` : `[${camelToKebab(a.name)}]`))
    .join(' ');
  const cmdName = argStr ? `${method.cliName} ${argStr}` : method.cliName;
  const httpHint = method.httpMethod ? ` [${method.httpMethod}]` : '';

  lines.push(`  ${parentVar}.command('${cmdName}')`);
  lines.push(`    .description('${method.description}${httpHint}')`);
  for (const opt of method.options) {
    const flag = opt.type === 'boolean' ? `--${opt.name}` : `--${opt.name} <value>`;
    const defaultSuffix = opt.defaultValue !== undefined ? `, ${JSON.stringify(opt.defaultValue)}` : '';
    if (opt.required) {
      lines.push(`    .requiredOption('${flag}', '${opt.description}'${defaultSuffix})`);
    } else {
      lines.push(`    .option('${flag}', '${opt.description}'${defaultSuffix})`);
    }
  }
  lines.push(`    .option('--json', 'Output raw JSON')`);

  const actionParams = [...method.args.map((a) => a.name), 'opts'].join(', ');
  lines.push(`    .action(async (${actionParams}) => {`);
  lines.push(`      try {`);

  // Resolve the API (async for most services, sync for storage)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any — dynamic Proxy objects
  if (asyncApi) {
    const accessor = subGroupName
      ? `(await ${apiExpr}).${subGroupName}`
      : `await ${apiExpr}`;
    lines.push(`        const api: any = ${accessor};`);
  } else {
    const accessor = subGroupName ? `${apiExpr}.${subGroupName}` : apiExpr;
    lines.push(`        const api: any = ${accessor};`);
  }

  const { preamble, callArgs } = buildCallArgs(method);
  if (preamble) lines.push(preamble.trimEnd());
  const httpMethod = method.httpMethod ?? 'GET';
  const urlTemplate = method.urlTemplate;
  const idCount = method.idCount;
  const callArgStr = callArgs ? `, ${callArgs}` : '';

  if (method.textBody) {
    // textBody methods send plain text body + query params (e.g. encryption encrypt)
    const textArgName = method.textBody;
    const queryOpts = method.options.map((o) => {
      const cn = kebabToCamel(o.name);
      return `${cn}: opts['${cn}']`;
    });
    const queryObj = queryOpts.length > 0 ? `{ ${queryOpts.join(', ')} }` : 'undefined';
    lines.push(`        const result = await api._callText('${method.name}', '${httpMethod}', '${urlTemplate}', ${textArgName}, ${queryObj});`);
  } else if (method.queryParams && method.queryParams.length > 0) {
    // Methods with both JSON body and query params (e.g. encryptSecrets)
    const qpCamel = method.queryParams.map(kebabToCamel);
    lines.push(`        const __qp = new URLSearchParams();`);
    for (const cn of qpCamel) {
      lines.push(`        if (opts['${cn}'] !== undefined) __qp.set('${cn}', String(opts['${cn}']));`);
    }
    lines.push(`        const __qs = __qp.toString();`);
    lines.push(`        const __url = __qs ? '${urlTemplate}?' + __qs : '${urlTemplate}';`);
    lines.push(`        const result = await api._call('${method.name}', '${httpMethod}', __url, ${idCount}${callArgStr});`);
  } else {
    lines.push(`        const result = await api._call('${method.name}', '${httpMethod}', '${urlTemplate}', ${idCount}${callArgStr});`);
  }
  lines.push(`        ctx.output(result);`);
  lines.push(`      } catch (error: unknown) {`);
  lines.push(`        ctx.handleError(error);`);
  lines.push(`      }`);
  lines.push(`    });`);

  return lines.join('\n');
}

function generateServiceFile(service: ServiceDef): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push('');

  const fnName = `register${pascalCase(service.name)}Commands`;
  const apiCall = getApiCall(service);
  const asyncApi = isAsyncApi(service);

  lines.push(`export function ${fnName}(parent: Command, ctx: CliContext) {`);
  lines.push(`  const service = parent.command('${service.cliName}').description('${service.description}');`);
  lines.push('');

  for (const method of service.methods) {
    lines.push(generateCommand(method, 'service', apiCall, asyncApi));
    lines.push('');
  }

  for (const group of service.subGroups) {
    const gv = `group_${group.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
    lines.push(`  const ${gv} = service.command('${group.cliName}').description('${group.description}');`);
    lines.push('');
    for (const method of group.methods) {
      lines.push(generateCommand(method, gv, apiCall, asyncApi, group.name));
      lines.push('');
    }
  }

  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

function generateRegistryFile(): string {
  const lines: string[] = [HEADER];
  lines.push(`export type AtomicMethod = { service: string; subGroup: string | null; method: string; cliPath: string; };`);
  lines.push('');
  lines.push(`export const ATOMIC_METHODS: AtomicMethod[] = [`);
  for (const service of API_REGISTRY) {
    for (const m of service.methods) {
      lines.push(`  { service: '${service.name}', subGroup: null, method: '${m.name}', cliPath: '${service.cliName} ${m.cliName}' },`);
    }
    for (const g of service.subGroups) {
      for (const m of g.methods) {
        lines.push(`  { service: '${service.name}', subGroup: '${g.name}', method: '${m.name}', cliPath: '${service.cliName} ${g.cliName} ${m.cliName}' },`);
      }
    }
  }
  lines.push(`];`);
  lines.push('');
  lines.push(`export const METHOD_MAP = new Map(ATOMIC_METHODS.map((m) => [\`\${m.service}.\${m.subGroup ? m.subGroup + '.' : ''}\${m.method}\`, m]));`);
  lines.push('');
  const { total } = countMethods();
  lines.push(`/** Total atomic methods: ${total} */`);
  lines.push(`export const TOTAL_METHODS = ${total};`);
  lines.push('');
  return lines.join('\n');
}


// ─── Layer 2: Logical Unit Generation ────────────────────────────────

const UNITS_DIR = path.resolve(import.meta.dir, '../src/units');
const LOGICAL_UNITS_PATH = path.resolve(import.meta.dir, 'logical-units.json');

function loadLogicalUnits(): LogicalUnitsFile {
  const raw = fs.readFileSync(LOGICAL_UNITS_PATH, 'utf-8');
  return JSON.parse(raw) as LogicalUnitsFile;
}

/** Get the CliContext API accessor expression for a service name */
function getUnitApiExpr(serviceName: string): string {
  const map: Record<string, string> = {
    'data-science': 'ctx.dataScienceApi()',
    'storage': 'ctx.storageApi()',
    'vault': 'ctx.vaultApi()',
    'management': 'ctx.managementApi()',
    'queue': 'ctx.queueApi()',
    'sandboxes': 'ctx.sandboxesApi()',
    'editor': 'ctx.editorApi()',
    'encryption': 'ctx.encryptionApi()',
    'chat': 'ctx.chatApi()',
    'ai': 'ctx.aiApi()',
    'query-service': 'ctx.queryServiceApi()',
    'metastore': 'ctx.metastoreApi()',
    'sync-actions': 'ctx.syncActionsApi()',
    'status': 'ctx.statusApi()',
    'assets': 'ctx.assetsApi()',
    'telemetry': 'ctx.telemetryApi()',
  };
  return map[serviceName] ?? `ctx.genericServiceApi('${serviceName}')`;
}

function isUnitApiAsync(serviceName: string): boolean {
  return serviceName !== 'storage';
}

function generateUnitCommand(cmd: UnitCommandDef): string {
  const lines: string[] = [];
  const asyncApi = isUnitApiAsync(cmd.service);
  const apiExpr = getUnitApiExpr(cmd.service);

  // Build argument string for Commander
  const argStr = cmd.args
    .map((a) => (a.required ? `<${camelToKebab(a.name)}>` : `[${camelToKebab(a.name)}]`))
    .join(' ');
  const cmdStr = argStr ? `${cmd.name} ${argStr}` : cmd.name;

  lines.push(`  unit.command('${cmdStr}')`);
  lines.push(`    .description('${cmd.description}')`);

  // Register options
  for (const opt of cmd.options) {
    const flag = opt.type === 'boolean' ? `--${opt.name}` : `--${opt.name} <value>`;
    const defaultSuffix = opt.defaultValue !== undefined ? `, ${JSON.stringify(opt.defaultValue)}` : '';
    if (opt.required) {
      lines.push(`    .requiredOption('${flag}', '${opt.description}'${defaultSuffix})`);
    } else {
      lines.push(`    .option('${flag}', '${opt.description}'${defaultSuffix})`);
    }
  }
  lines.push(`    .option('--json', 'Output raw JSON')`);

  const actionParams = [...cmd.args.map((a) => a.name), 'opts'].join(', ');
  lines.push(`    .action(async (${actionParams}) => {`);
  lines.push(`      try {`);

  // Resolve API proxy
  if (asyncApi) {
    const accessor = cmd.subGroup
      ? `(await ${apiExpr}).${cmd.subGroup}`
      : `await ${apiExpr}`;
    lines.push(`        const api: any = ${accessor};`);
  } else {
    const accessor = cmd.subGroup
      ? `${apiExpr}.${cmd.subGroup}`
      : apiExpr;
    lines.push(`        const api: any = ${accessor};`);
  }

  // Build call based on whether we have buildBody or standard _call
  if (cmd.buildBody) {
    // Custom body construction from args/options
    const bodyEntries: string[] = [];
    for (const [key, value] of Object.entries(cmd.buildBody)) {
      if (value.startsWith('$')) {
        const varName = value.slice(1);
        // Check if it's an arg or an option
        const isArg = cmd.args.some((a) => a.name === varName);
        if (isArg) {
          bodyEntries.push(`${key}: ${varName}`);
        } else {
          bodyEntries.push(`${key}: opts['${camelToKebab(varName)}'] ?? opts['${varName}']`);
        }
      } else {
        bodyEntries.push(`${key}: ${JSON.stringify(value)}`);
      }
    }
    lines.push(`        const body = { ${bodyEntries.join(', ')} };`);
    lines.push(`        const result = await api._call('${cmd.atomicRef.split('.').pop()}', '${cmd.httpMethod}', '${cmd.urlTemplate}', ${cmd.idCount}, body);`);
  } else {
    // Standard _call with positional + options
    const callParts: string[] = [];

    // Handle hardcoded args (e.g. component ID for flows)
    const maxId = cmd.idCount;
    for (let i = 0; i < maxId; i++) {
      const iStr = String(i);
      if (cmd.hardcodedArgs && cmd.hardcodedArgs[iStr]) {
        callParts.push(JSON.stringify(cmd.hardcodedArgs[iStr]));
      } else if (cmd.argMapping) {
        // Find which arg maps to this position
        const mappedArg = Object.entries(cmd.argMapping).find(([, pos]) => pos === i);
        if (mappedArg) {
          callParts.push(mappedArg[0]);
        } else {
          callParts.push(`undefined`);
        }
      } else {
        // Direct positional arg
        if (i < cmd.args.length) {
          callParts.push(cmd.args[i]!.name);
        }
      }
    }

    // Build options object
    const optEntries: string[] = [];
    for (const opt of cmd.options) {
      const cn = kebabToCamel(opt.name);
      optEntries.push(`${cn}: opts['${cn}']`);
    }
    if (cmd.queryDefaults) {
      for (const [key, value] of Object.entries(cmd.queryDefaults)) {
        optEntries.push(`${key}: ${JSON.stringify(value)}`);
      }
    }

    if (optEntries.length > 0) {
      callParts.push(`{ ${optEntries.join(', ')} }`);
    }

    const callArgStr = callParts.length > 0 ? `, ${callParts.join(', ')}` : '';
    const methodNamePart = cmd.atomicRef.split('.').pop()!;
    lines.push(`        const result = await api._call('${methodNamePart}', '${cmd.httpMethod}', '${cmd.urlTemplate}', ${cmd.idCount}${callArgStr});`);
  }

  // Output handling
  lines.push(`        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }`);

  if (cmd.table) {
    // Table output
    if (cmd.table.flatten) {
      // Response is array of components with nested configs — flatten them
      lines.push(`        const components = Array.isArray(result) ? result : [];`);
      lines.push(`        const items: any[] = [];`);
      lines.push(`        for (const comp of components) {`);
      lines.push(`          const nested = comp['${cmd.table.flatten}'];`);
      lines.push(`          if (Array.isArray(nested)) {`);
      lines.push(`            for (const item of nested) items.push(item);`);
      lines.push(`          }`);
      lines.push(`        }`);
    } else {
      lines.push(`        const items = Array.isArray(result) ? result : [];`);
    }
    lines.push(`        if (items.length === 0) { console.log('${cmd.table.emptyMessage}'); return; }`);

    // Build row mapping
    const rowEntries = cmd.table.columns.map((col) => {
      const val = col.maxWidth
        ? `String(item['${col.key}'] ?? '').slice(0, ${col.maxWidth})`
        : `item['${col.key}'] ?? ''`;
      return `'${col.label ?? col.key}': ${val}`;
    });
    lines.push(`        const rows = items.map((item: any) => ({ ${rowEntries.join(', ')} }));`);
    lines.push(`        console.log(formatTable(rows));`);
  } else {
    // Default JSON output for detail commands
    lines.push(`        console.log(JSON.stringify(result, null, 2));`);
  }

  lines.push(`      } catch (error: unknown) {`);
  lines.push(`        ctx.handleError(error);`);
  lines.push(`      }`);
  lines.push(`    });`);

  return lines.join('\n');
}

function generateUnitFile(unit: UnitDef): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push(`import { formatTable } from '../output';`);
  lines.push('');

  const fnName = `register${pascalCase(unit.name)}Unit`;
  lines.push(`export function ${fnName}(parent: Command, ctx: CliContext) {`);
  lines.push(`  const unit = parent.command('${unit.name}').description('${unit.description}');`);
  lines.push('');

  for (const cmd of unit.commands) {
    lines.push(generateUnitCommand(cmd));
    lines.push('');
  }

  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

function generateUnitsIndexFile(units: UnitDef[]): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push('');
  for (const u of units) {
    lines.push(`import { register${pascalCase(u.name)}Unit } from './${u.name}';`);
  }
  lines.push('');
  lines.push(`export function registerAllLogicalUnits(program: Command, ctx: CliContext) {`);
  for (const u of units) {
    lines.push(`  register${pascalCase(u.name)}Unit(program, ctx);`);
  }
  lines.push(`}`);
  lines.push('');
  lines.push(`export const UNIT_NAMES = [${units.map((u) => `'${u.name}'`).join(', ')}] as const;`);
  lines.push(`export const UNIT_COUNT = ${units.length};`);
  lines.push(`export const UNIT_COMMAND_COUNT = ${units.reduce((sum, u) => sum + u.commands.length, 0)};`);
  lines.push('');
  return lines.join('\n');
}

/** Validate that all atomicRef values exist in the API registry */
function validateLogicalUnits(units: UnitDef[]): { ok: boolean; errors: string[] } {
  const errors: string[] = [];

  // Build a set of all known atomic method keys
  const knownMethods = new Set<string>();
  for (const service of API_REGISTRY) {
    for (const m of service.methods) {
      knownMethods.add(`${service.name}.${m.name}`);
    }
    for (const g of service.subGroups) {
      for (const m of g.methods) {
        knownMethods.add(`${service.name}.${g.name}.${m.name}`);
      }
    }
  }

  for (const unit of units) {
    for (const cmd of unit.commands) {
      if (!knownMethods.has(cmd.atomicRef)) {
        errors.push(`[${unit.name}.${cmd.name}] atomicRef '${cmd.atomicRef}' not found in api-registry`);
      }
    }
  }

  return { ok: errors.length === 0, errors };
}

// ─── Original Index File ─────────────────────────────────────────────

function generateIndexFile(): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push('');
  for (const s of API_REGISTRY) {
    lines.push(`import { register${pascalCase(s.name)}Commands } from './${s.cliName}';`);
  }
  lines.push('');
  lines.push(`export function registerAllGeneratedCommands(program: Command, ctx: CliContext) {`);
  for (const s of API_REGISTRY) {
    lines.push(`  register${pascalCase(s.name)}Commands(program, ctx);`);
  }
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

// ─── SKILL.md Generation ──────────────────────────────────────────────

function generateSkillMd(logicalUnits: LogicalUnitsFile): string {
  const { total } = countMethods();
  const lines: string[] = [];

  lines.push('# Keboola CLI (kbc) — AI Agent Skill Reference');
  lines.push('');
  lines.push('<!-- AUTO-GENERATED by generator/generate.ts — DO NOT EDIT -->');
  lines.push('<!-- Re-generate with: make generate -->');
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push(`Complete CLI over the entire Keboola API. Two command layers:`);
  lines.push('');
  lines.push(`- **Layer 1 — Atomic commands** (${total} commands): 1:1 mapping to every Keboola API method across ${API_REGISTRY.length} services`);
  lines.push(`- **Layer 2 — Logical units** (${logicalUnits.units.length} units, ${logicalUnits.units.reduce((s, u) => s + u.commands.length, 0)} commands): High-level domain-oriented commands with table formatting and smart defaults`);
  lines.push('');
  lines.push('## Authentication');
  lines.push('');
  lines.push('```bash');
  lines.push('kbc auth login --token <STORAGE_API_TOKEN> --url <STACK_URL>');
  lines.push('```');
  lines.push('');
  lines.push('Or via environment variables: `KBC_STORAGE_TOKEN`, `KBC_STORAGE_URL`');
  lines.push('');
  lines.push('## Logical Units');
  lines.push('');

  for (const unit of logicalUnits.units) {
    lines.push(`### \`kbc ${unit.name}\` — ${unit.description}`);
    lines.push('');
    if (unit.skillDescription) {
      lines.push(unit.skillDescription);
      lines.push('');
    }
    lines.push('| Command | Description |');
    lines.push('|---------|-------------|');
    for (const cmd of unit.commands) {
      const argStr = cmd.args
        .map((a) => (a.required ? `<${a.name}>` : `[${a.name}]`))
        .join(' ');
      const fullCmd = argStr ? `${cmd.name} ${argStr}` : cmd.name;
      lines.push(`| \`kbc ${unit.name} ${fullCmd}\` | ${cmd.description} |`);
    }
    lines.push('');
  }

  lines.push('## Hand-Written Units');
  lines.push('');
  lines.push('These units have custom logic beyond simple API calls:');
  lines.push('');

  const handWritten = [
    { name: 'data-app', description: 'Manage Data Apps (deploy, logs, start/stop, open in browser)', skill: 'Use for deploying and managing Data Apps. Typical workflow: list apps → use <app-id> → deploy --follow → logs → open. Supports full lifecycle management including deploy with log streaming.' },
    { name: 'auth', description: 'Authentication (login, logout, status, profiles)', skill: 'Use to authenticate with Keboola. Run `kbc auth login` to set up credentials. Supports multiple profiles for different stacks.' },
    { name: 'use', description: 'Set active Data App context', skill: 'Use to set the active Data App ID so subsequent commands don\'t need --app flag.' },
    { name: 'secrets', description: 'Manage Data App secrets (list, set, delete, import from .env)', skill: 'Use to manage environment variables/secrets for Data Apps. Supports bulk import from .env files.' },
    { name: 'runs', description: 'View Data App deployment runs', skill: 'Use to inspect deployment history and run details for Data Apps.' },
    { name: 'config', description: 'CLI configuration (show, set, git integration)', skill: 'Use to manage CLI settings and git integration for Data App deployment.' },
    { name: 'api', description: 'Raw API calls (any method, any URL)', skill: 'Use for advanced/custom API calls not covered by other units. Supports any HTTP method and arbitrary URL paths.' },
  ];

  for (const hw of handWritten) {
    lines.push(`### \`kbc ${hw.name}\` — ${hw.description}`);
    lines.push('');
    lines.push(hw.skill);
    lines.push('');
  }

  lines.push('## Layer 1 — Atomic Commands');
  lines.push('');
  lines.push('Low-level 1:1 API method mappings organized by service. Use `--json` flag for machine-readable output.');
  lines.push('');

  for (const service of API_REGISTRY) {
    const methodCount = service.methods.length + service.subGroups.reduce((sum, g) => sum + g.methods.length, 0);
    lines.push(`- \`kbc ${service.cliName}\` — ${service.description} (${methodCount} commands)`);
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated from ${logicalUnits.units.length} logical units + ${API_REGISTRY.length} API services = ${total + logicalUnits.units.reduce((s, u) => s + u.commands.length, 0)} total commands*`);
  lines.push('');

  return lines.join('\n');
}

// ─── Main ─────────────────────────────────────────────────────────────

async function main() {
  const verifyOnly = process.argv.includes('--verify-only');

  console.log('API Registry Stats:');
  const { total, byService } = countMethods();
  for (const [name, count] of Object.entries(byService)) {
    console.log(`  ${name}: ${count} methods`);
  }
  console.log(`  TOTAL: ${total} methods`);
  console.log('');

  // Verify registry against source
  console.log('Verifying registry against api-client source...');
  const result = verifyRegistry();

  for (const warning of result.warnings) {
    console.log(`  WARN: ${warning}`);
  }
  for (const error of result.errors) {
    console.log(`  ERROR: ${error}`);
  }

  if (!result.ok) {
    console.error('\nRegistry verification failed! Fix errors above.');
    process.exit(1);
  }

  console.log(`\nVerification passed (${result.warnings.length} warnings).`);

  if (verifyOnly) {
    console.log('Verify-only mode, skipping generation.');
    return;
  }

  // Generate files
  console.log('\nGenerating CLI commands...');

  // Ensure output directory exists
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  // Generate service files
  for (const service of API_REGISTRY) {
    const filePath = path.join(GENERATED_DIR, `${service.cliName}.ts`);
    fs.writeFileSync(filePath, generateServiceFile(service));
    const methodCount = service.methods.length + service.subGroups.reduce((sum, g) => sum + g.methods.length, 0);
    console.log(`  ${service.cliName}.ts (${methodCount} commands)`);
  }

  // Generate registry file
  const registryPath = path.join(GENERATED_DIR, '_registry.ts');
  fs.writeFileSync(registryPath, generateRegistryFile());
  console.log(`  _registry.ts`);

  // Generate index file
  const indexPath = path.join(GENERATED_DIR, 'index.ts');
  fs.writeFileSync(indexPath, generateIndexFile());
  console.log(`  index.ts`);

  console.log(`\nGeneration complete! ${total} atomic commands across ${API_REGISTRY.length} services.`);

  // ─── Layer 2: Logical Units ─────────────────────────────────────
  console.log('\nGenerating Layer 2 logical units...');

  const logicalUnits = loadLogicalUnits();

  // Validate atomicRef references
  const unitValidation = validateLogicalUnits(logicalUnits.units);
  for (const err of unitValidation.errors) {
    console.log(`  ERROR: ${err}`);
  }
  if (!unitValidation.ok) {
    console.error('\nLogical unit validation failed! Fix atomicRef errors above.');
    process.exit(1);
  }
  console.log(`  Validation passed (${logicalUnits.units.length} units).`);

  // Ensure units output directory exists
  fs.mkdirSync(UNITS_DIR, { recursive: true });

  // Generate unit files
  for (const unit of logicalUnits.units) {
    const filePath = path.join(UNITS_DIR, `${unit.name}.ts`);
    fs.writeFileSync(filePath, generateUnitFile(unit));
    console.log(`  units/${unit.name}.ts (${unit.commands.length} commands)`);
  }

  // Generate units index (named _generated.ts to avoid conflict with hand-written index.ts)
  const unitsIndexPath = path.join(UNITS_DIR, '_generated.ts');
  fs.writeFileSync(unitsIndexPath, generateUnitsIndexFile(logicalUnits.units));
  console.log(`  units/_generated.ts`);

  const totalUnitCommands = logicalUnits.units.reduce((s, u) => s + u.commands.length, 0);
  console.log(`\nLayer 2 complete! ${totalUnitCommands} unit commands across ${logicalUnits.units.length} logical units.`);

  // Generate SKILL.md
  const skillMd = generateSkillMd(logicalUnits);
  const skillPath = path.resolve(import.meta.dir, '../SKILL.md');
  fs.writeFileSync(skillPath, skillMd);
  console.log(`\nGenerated SKILL.md`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
