#!/usr/bin/env bun
/**
 * CLI Generator — reads api-registry.ts and generates Commander.js commands.
 *
 * Usage: bun run generator/generate.ts [--verify-only]
 *
 * - Without flags: generates src/generated/*.ts files
 * - With --verify-only: only verifies registry against api-client source (no file output)
 */

import * as fs from 'fs';
import * as path from 'path';
import { API_REGISTRY, countMethods, type ServiceDef, type MethodDef } from './api-registry';

const GENERATED_DIR = path.resolve(import.meta.dir, '../src/generated');
const HEADER = `// AUTO-GENERATED by generator/generate.ts — DO NOT EDIT
// Re-generate with: make generate
`;

// ─── Verification ─────────────────────────────────────────────────────

const API_CLIENT_DIR = path.resolve(import.meta.dir, '../../ui/packages/api-client/src/clients');

function extractExportedMethods(filePath: string): string[] {
  if (!fs.existsSync(filePath)) {
    return [];
  }
  const source = fs.readFileSync(filePath, 'utf-8');

  // Find the return { ... } block at the end of the factory function
  // We look for the last return { ... }; pattern
  const returnBlocks = source.matchAll(/return\s*\{([^}]+)\}/g);
  let lastMatch: string | null = null;
  for (const match of returnBlocks) {
    lastMatch = match[1]!;
  }

  if (!lastMatch) return [];

  // Extract method names from the return object
  return lastMatch
    .split(',')
    .map((s) => s.replace(/\/\/.*$/gm, '').trim()) // remove comments
    .filter((s) => s.length > 0 && !s.startsWith('//'))
    .map((s) => {
      // Handle "foo: bar" and just "foo"
      const colonIndex = s.indexOf(':');
      if (colonIndex > 0) {
        return s.substring(0, colonIndex).trim();
      }
      return s.trim();
    })
    .filter((s) => s.length > 0 && /^[a-zA-Z_]/.test(s));
}

type VerifyResult = {
  ok: boolean;
  errors: string[];
  warnings: string[];
};

function verifyRegistry(): VerifyResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  for (const service of API_REGISTRY) {
    const clientDir = path.join(API_CLIENT_DIR, service.sourceDir);

    if (!fs.existsSync(clientDir)) {
      warnings.push(`[${service.name}] Source directory not found: ${clientDir}`);
      continue;
    }

    // Verify direct methods on the main client file
    const mainFile = path.join(clientDir, service.clientFile);
    const mainMethods = extractExportedMethods(mainFile);

    for (const method of service.methods) {
      // Skip methods that are actually on sub-objects (handled by sub-groups)
      if (!mainMethods.includes(method.name)) {
        // Check if it might be a private method (prefixed with _)
        if (!mainMethods.includes(`_${method.name}`)) {
          errors.push(`[${service.name}] Method '${method.name}' not found in ${service.clientFile}. Available: ${mainMethods.join(', ')}`);
        }
      }
    }

    // Verify sub-group methods
    for (const group of service.subGroups) {
      const subFile = path.join(clientDir, group.sourceFile);
      const subMethods = extractExportedMethods(subFile);

      if (subMethods.length === 0) {
        warnings.push(`[${service.name}.${group.name}] No methods found in ${group.sourceFile}`);
        continue;
      }

      for (const method of group.methods) {
        if (!subMethods.includes(method.name)) {
          errors.push(`[${service.name}.${group.name}] Method '${method.name}' not found in ${group.sourceFile}. Available: ${subMethods.join(', ')}`);
        }
      }

      // Warn about methods in source but not in registry
      const registeredNames = new Set(group.methods.map((m) => m.name));
      for (const srcMethod of subMethods) {
        if (!registeredNames.has(srcMethod) && !srcMethod.startsWith('_')) {
          warnings.push(`[${service.name}.${group.name}] Method '${srcMethod}' exists in source but not in registry`);
        }
      }
    }

    // Warn about methods in source but not in registry (direct methods)
    const registeredDirectNames = new Set(service.methods.map((m) => m.name));
    // For the main client, also collect sub-group names (they appear in return)
    const subGroupNames = new Set(service.subGroups.map((g) => g.name));
    for (const srcMethod of mainMethods) {
      if (!registeredDirectNames.has(srcMethod) && !subGroupNames.has(srcMethod) && !srcMethod.startsWith('_')) {
        warnings.push(`[${service.name}] Method '${srcMethod}' exists in source but not in registry`);
      }
    }
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
  };
}

// ─── Code Generation ──────────────────────────────────────────────────

function camelToKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function kebabToCamel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function pascalCase(name: string): string {
  return name.split('-').map((s) => s[0]!.toUpperCase() + s.slice(1)).join('');
}

/** Map service to its CliContext accessor. All are async except storage. */
function getApiCall(service: ServiceDef): string {
  const map: Record<string, string> = {
    'data-science': 'ctx.dataScienceApi()',
    'storage': 'ctx.storageApi()',
    'vault': 'ctx.vaultApi()',
    'management': 'ctx.managementApi()',
    'queue': 'ctx.queueApi()',
    'sandboxes': 'ctx.sandboxesApi()',
    'editor': 'ctx.editorApi()',
    'encryption': 'ctx.encryptionApi()',
    'chat': 'ctx.chatApi()',
    'ai': 'ctx.aiApi()',
    'query-service': 'ctx.queryServiceApi()',
    'metastore': 'ctx.metastoreApi()',
    'sync-actions': 'ctx.syncActionsApi()',
    'status': 'ctx.statusApi()',
    'assets': 'ctx.assetsApi()',
  };
  return map[service.name] ?? `ctx.genericServiceApi('${service.name}')`;
}

function isAsyncApi(service: ServiceDef): boolean {
  return service.name !== 'storage';
}

function buildCallArgs(method: MethodDef): { preamble: string; callArgs: string } {
  const hasJsonData = method.options.some((o) => o.type === 'json' && o.name === 'data');
  let preamble = '';
  if (hasJsonData) {
    preamble = `        const bodyData = opts.data ? JSON.parse(opts.data) : {};\n`;
  }
  const args: string[] = [];
  for (const arg of method.args) {
    args.push(arg.type === 'number' ? `Number(${arg.name})` : arg.name);
  }
  const nonDataOpts = method.options.filter((o) => o.name !== 'data');
  if (hasJsonData && nonDataOpts.length === 0) {
    args.push('bodyData');
  } else if (hasJsonData && nonDataOpts.length > 0) {
    const extras = nonDataOpts.map((o) => `${kebabToCamel(o.name)}: opts['${o.name}']`).join(', ');
    args.push(`{ ...bodyData, ${extras} }`);
  } else if (nonDataOpts.length > 0 && !hasJsonData) {
    const optEntries = nonDataOpts.map((o) => {
      const cn = kebabToCamel(o.name);
      return o.type === 'number'
        ? `${cn}: opts['${o.name}'] !== undefined ? Number(opts['${o.name}']) : undefined`
        : `${cn}: opts['${o.name}']`;
    }).join(', ');
    args.push(`{ ${optEntries} }`);
  }
  return { preamble, callArgs: args.join(', ') };
}

function generateCommand(
  method: MethodDef,
  parentVar: string,
  apiExpr: string,
  asyncApi: boolean,
  subGroupName?: string,
): string {
  const lines: string[] = [];
  const argStr = method.args
    .map((a) => (a.required ? `<${camelToKebab(a.name)}>` : `[${camelToKebab(a.name)}]`))
    .join(' ');
  const cmdName = argStr ? `${method.cliName} ${argStr}` : method.cliName;
  const httpHint = method.httpMethod ? ` [${method.httpMethod}]` : '';

  lines.push(`  ${parentVar}.command('${cmdName}')`);
  lines.push(`    .description('${method.description}${httpHint}')`);
  for (const opt of method.options) {
    const flag = opt.type === 'boolean' ? `--${opt.name}` : `--${opt.name} <value>`;
    const req = opt.required ? ' (required)' : '';
    lines.push(`    .option('${flag}', '${opt.description}${req}')`);
  }
  lines.push(`    .option('--json', 'Output raw JSON')`);

  const actionParams = [...method.args.map((a) => a.name), 'opts'].join(', ');
  lines.push(`    .action(async (${actionParams}) => {`);
  lines.push(`      try {`);

  // Resolve the API (async for most services, sync for storage)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any — dynamic Proxy objects
  if (asyncApi) {
    const accessor = subGroupName
      ? `(await ${apiExpr}).${subGroupName}`
      : `await ${apiExpr}`;
    lines.push(`        const api: any = ${accessor};`);
  } else {
    const accessor = subGroupName ? `${apiExpr}.${subGroupName}` : apiExpr;
    lines.push(`        const api: any = ${accessor};`);
  }

  const { preamble, callArgs } = buildCallArgs(method);
  if (preamble) lines.push(preamble.trimEnd());
  const httpMethod = method.httpMethod ?? 'GET';
  const urlTemplate = method.urlTemplate;
  const idCount = method.idCount;
  const callArgStr = callArgs ? `, ${callArgs}` : '';
  lines.push(`        const result = await api._call('${method.name}', '${httpMethod}', '${urlTemplate}', ${idCount}${callArgStr});`);
  lines.push(`        ctx.output(result);`);
  lines.push(`      } catch (error: unknown) {`);
  lines.push(`        ctx.handleError(error);`);
  lines.push(`      }`);
  lines.push(`    });`);

  return lines.join('\n');
}

function generateServiceFile(service: ServiceDef): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push('');

  const fnName = `register${pascalCase(service.name)}Commands`;
  const apiCall = getApiCall(service);
  const asyncApi = isAsyncApi(service);

  lines.push(`export function ${fnName}(parent: Command, ctx: CliContext) {`);
  lines.push(`  const service = parent.command('${service.cliName}').description('${service.description}');`);
  lines.push('');

  for (const method of service.methods) {
    lines.push(generateCommand(method, 'service', apiCall, asyncApi));
    lines.push('');
  }

  for (const group of service.subGroups) {
    const gv = `group_${group.name.replace(/[^a-zA-Z0-9]/g, '_')}`;
    lines.push(`  const ${gv} = service.command('${group.cliName}').description('${group.description}');`);
    lines.push('');
    for (const method of group.methods) {
      lines.push(generateCommand(method, gv, apiCall, asyncApi, group.name));
      lines.push('');
    }
  }

  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

function generateRegistryFile(): string {
  const lines: string[] = [HEADER];
  lines.push(`export type AtomicMethod = { service: string; subGroup: string | null; method: string; cliPath: string; };`);
  lines.push('');
  lines.push(`export const ATOMIC_METHODS: AtomicMethod[] = [`);
  for (const service of API_REGISTRY) {
    for (const m of service.methods) {
      lines.push(`  { service: '${service.name}', subGroup: null, method: '${m.name}', cliPath: '${service.cliName} ${m.cliName}' },`);
    }
    for (const g of service.subGroups) {
      for (const m of g.methods) {
        lines.push(`  { service: '${service.name}', subGroup: '${g.name}', method: '${m.name}', cliPath: '${service.cliName} ${g.cliName} ${m.cliName}' },`);
      }
    }
  }
  lines.push(`];`);
  lines.push('');
  lines.push(`export const METHOD_MAP = new Map(ATOMIC_METHODS.map((m) => [\`\${m.service}.\${m.subGroup ? m.subGroup + '.' : ''}\${m.method}\`, m]));`);
  lines.push('');
  const { total } = countMethods();
  lines.push(`/** Total atomic methods: ${total} */`);
  lines.push(`export const TOTAL_METHODS = ${total};`);
  lines.push('');
  return lines.join('\n');
}


function generateIndexFile(): string {
  const lines: string[] = [HEADER];
  lines.push(`import { Command } from 'commander';`);
  lines.push(`import type { CliContext } from '../context';`);
  lines.push('');
  for (const s of API_REGISTRY) {
    lines.push(`import { register${pascalCase(s.name)}Commands } from './${s.cliName}';`);
  }
  lines.push('');
  lines.push(`export function registerAllGeneratedCommands(program: Command, ctx: CliContext) {`);
  for (const s of API_REGISTRY) {
    lines.push(`  register${pascalCase(s.name)}Commands(program, ctx);`);
  }
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

// ─── Main ─────────────────────────────────────────────────────────────

async function main() {
  const verifyOnly = process.argv.includes('--verify-only');

  console.log('API Registry Stats:');
  const { total, byService } = countMethods();
  for (const [name, count] of Object.entries(byService)) {
    console.log(`  ${name}: ${count} methods`);
  }
  console.log(`  TOTAL: ${total} methods`);
  console.log('');

  // Verify registry against source
  console.log('Verifying registry against api-client source...');
  const result = verifyRegistry();

  for (const warning of result.warnings) {
    console.log(`  WARN: ${warning}`);
  }
  for (const error of result.errors) {
    console.log(`  ERROR: ${error}`);
  }

  if (!result.ok) {
    console.error('\nRegistry verification failed! Fix errors above.');
    process.exit(1);
  }

  console.log(`\nVerification passed (${result.warnings.length} warnings).`);

  if (verifyOnly) {
    console.log('Verify-only mode, skipping generation.');
    return;
  }

  // Generate files
  console.log('\nGenerating CLI commands...');

  // Ensure output directory exists
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  // Generate service files
  for (const service of API_REGISTRY) {
    const filePath = path.join(GENERATED_DIR, `${service.cliName}.ts`);
    fs.writeFileSync(filePath, generateServiceFile(service));
    const methodCount = service.methods.length + service.subGroups.reduce((sum, g) => sum + g.methods.length, 0);
    console.log(`  ${service.cliName}.ts (${methodCount} commands)`);
  }

  // Generate registry file
  const registryPath = path.join(GENERATED_DIR, '_registry.ts');
  fs.writeFileSync(registryPath, generateRegistryFile());
  console.log(`  _registry.ts`);

  // Generate index file
  const indexPath = path.join(GENERATED_DIR, 'index.ts');
  fs.writeFileSync(indexPath, generateIndexFile());
  console.log(`  index.ts`);

  console.log(`\nGeneration complete! ${total} atomic commands across ${API_REGISTRY.length} services.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
