// AUTO-GENERATED by generator/generate.ts — DO NOT EDIT
// Re-generate with: make generate

import { Command } from 'commander';
import type { CliContext } from '../context';
import { formatTable } from '../output';

export function registerBucketUnit(parent: Command, ctx: CliContext) {
  const unit = parent.command('bucket').description('Manage storage buckets');

  unit.command('list')
    .description('List all buckets in the project')
    .option('--json', 'Output raw JSON')
    .action(async (opts) => {
      try {
        const api: any = ctx.storageApi().buckets;
        const result = await api._call('getBuckets', 'GET', '/branch/default/buckets', 0);
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        const items = Array.isArray(result) ? result : [];
        if (items.length === 0) { console.log('No buckets found.'); return; }
        const rows = items.map((item: any) => ({ 'ID': item['id'] ?? '', 'Name': item['name'] ?? '', 'Stage': item['stage'] ?? '', 'Backend': item['backend'] ?? '', 'Rows': item['rowsCount'] ?? '', 'Size(B)': item['dataSizeBytes'] ?? '' }));
        console.log(formatTable(rows));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('show <bucket-id>')
    .description('Show bucket details')
    .option('--json', 'Output raw JSON')
    .action(async (bucketId, opts) => {
      try {
        const api: any = ctx.storageApi().buckets;
        const result = await api._call('getBucket', 'GET', '/branch/default/buckets/{0}', 1, bucketId);
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('create')
    .description('Create a new bucket')
    .requiredOption('--name <value>', 'Bucket name')
    .requiredOption('--stage <value>', 'Bucket stage (in, out)')
    .option('--backend <value>', 'Storage backend (snowflake, bigquery, etc.)')
    .option('--description <value>', 'Bucket description')
    .option('--json', 'Output raw JSON')
    .action(async (opts) => {
      try {
        const api: any = ctx.storageApi().buckets;
        const result = await api._call('createBucket', 'POST', '/branch/default/buckets', 0, { name: opts['name'], stage: opts['stage'], backend: opts['backend'], description: opts['description'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('delete <bucket-id>')
    .description('Delete a bucket')
    .option('--force', 'Force delete (including all tables)')
    .option('--json', 'Output raw JSON')
    .action(async (bucketId, opts) => {
      try {
        const api: any = ctx.storageApi().buckets;
        const result = await api._call('deleteBucket', 'DELETE', '/branch/default/buckets/{0}', 1, bucketId, { force: opts['force'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

}
