// AUTO-GENERATED by generator/generate.ts — DO NOT EDIT
// Re-generate with: make generate

import { Command } from 'commander';
import type { CliContext } from '../context';
import { formatTable } from '../output';

export function registerComponentUnit(parent: Command, ctx: CliContext) {
  const unit = parent.command('component').description('Manage components, configurations, and configuration rows');

  unit.command('list')
    .description('List all components in the project')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--type <value>', 'Filter by component type (extractor, writer, transformation, application)')
    .option('--json', 'Output raw JSON')
    .action(async (opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('getComponents', 'GET', '/branch/{branchId}/components', 0, { branchId: opts['branchId'], type: opts['type'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        const components = Array.isArray(result) ? result : [];
        const items: any[] = [];
        for (const comp of components) {
          const nested = comp['configurations'];
          if (Array.isArray(nested)) {
            for (const item of nested) items.push(item);
          }
        }
        if (items.length === 0) { console.log('No components found.'); return; }
        const rows = items.map((item: any) => ({ 'ID': item['id'] ?? '', 'Name': item['name'] ?? '', 'Description': String(item['description'] ?? '').slice(0, 50), 'Version': item['version'] ?? '' }));
        console.log(formatTable(rows));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('show <component-id>')
    .description('Show component details (schema, documentation)')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('getComponent', 'GET', '/branch/{branchId}/components/{0}', 1, componentId, { branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('configs <component-id>')
    .description('List configurations for a component')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('getConfigurations', 'GET', '/branch/{branchId}/components/{0}/configs', 1, componentId, { branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        const items = Array.isArray(result) ? result : [];
        if (items.length === 0) { console.log('No configurations found.'); return; }
        const rows = items.map((item: any) => ({ 'ID': item['id'] ?? '', 'Name': item['name'] ?? '', 'Description': String(item['description'] ?? '').slice(0, 60), 'Version': item['version'] ?? '', 'Created': item['created'] ?? '' }));
        console.log(formatTable(rows));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('config-show <component-id> <config-id>')
    .description('Show configuration details')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, configId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('getConfiguration', 'GET', '/branch/{branchId}/components/{0}/configs/{1}', 2, componentId, configId, { branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('config-create <component-id>')
    .description('Create a new configuration')
    .requiredOption('--name <value>', 'Configuration name')
    .option('--description <value>', 'Configuration description')
    .option('--data <value>', 'Configuration JSON data')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('createConfiguration', 'POST', '/branch/{branchId}/components/{0}/configs', 1, componentId, { name: opts['name'], description: opts['description'], data: opts['data'], branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('config-delete <component-id> <config-id>')
    .description('Delete a configuration')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, configId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('deleteConfiguration', 'DELETE', '/branch/{branchId}/components/{0}/configs/{1}', 2, componentId, configId, { branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('config-search')
    .description('Search configurations across all components')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--component-id <value>', 'Filter by component ID')
    .option('--config-id <value>', 'Filter by config ID')
    .option('--query <value>', 'Search query')
    .option('--json', 'Output raw JSON')
    .action(async (opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('searchComponentConfigurations', 'GET', '/branch/{branchId}/search/component-configurations', 0, { branchId: opts['branchId'], componentId: opts['componentId'], configId: opts['configId'], query: opts['query'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        const items = Array.isArray(result) ? result : [];
        if (items.length === 0) { console.log('No configurations found.'); return; }
        const rows = items.map((item: any) => ({ 'ID': item['id'] ?? '', 'Name': item['name'] ?? '', 'Description': String(item['description'] ?? '').slice(0, 50), 'Component': item['componentId'] ?? '' }));
        console.log(formatTable(rows));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('row-create <component-id> <config-id>')
    .description('Create a configuration row')
    .requiredOption('--data <value>', 'Row data as JSON')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--json', 'Output raw JSON')
    .action(async (componentId, configId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('createConfigurationRow', 'POST', '/branch/{branchId}/components/{0}/configs/{1}/rows', 2, componentId, configId, { data: opts['data'], branchId: opts['branchId'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

  unit.command('row-delete <component-id> <config-id> <row-id>')
    .description('Delete a configuration row')
    .option('--branch-id <value>', 'Branch ID', "default")
    .option('--change-description <value>', 'Change description')
    .option('--json', 'Output raw JSON')
    .action(async (componentId, configId, rowId, opts) => {
      try {
        const api: any = ctx.storageApi().componentsAndConfigurations;
        const result = await api._call('deleteConfigurationRow', 'DELETE', '/branch/{branchId}/components/{0}/configs/{1}/rows/{2}', 3, componentId, configId, rowId, { branchId: opts['branchId'], changeDescription: opts['changeDescription'] });
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

}
