// AUTO-GENERATED by generator/generate.ts — DO NOT EDIT
// Re-generate with: make generate

import { Command } from 'commander';
import type { CliContext } from '../context';
import { formatTable } from '../output';

export function registerTokenUnit(parent: Command, ctx: CliContext) {
  const unit = parent.command('token').description('Manage Storage API tokens');

  unit.command('verify')
    .description('Verify current token and show project info')
    .option('--json', 'Output raw JSON')
    .action(async (opts) => {
      try {
        const api: any = ctx.storageApi().tokens;
        const result = await api._call('verify', 'GET', '/tokens/verify', 0);
        if (opts.json) { console.log(JSON.stringify(result, null, 2)); return; }
        console.log(JSON.stringify(result, null, 2));
      } catch (error: unknown) {
        ctx.handleError(error);
      }
    });

}
